# Generated by Django 4.2.9 on 2024-05-25 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=254)),
                ('distribution_expenses', models.CharField(max_length=254)),
                ('book_image', models.ImageField(upload_to='storage/images')),
                ('book_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution_tracker.bookcat')),
            ],
        ),
    ]
