# Generated by Django 4.2.9 on 2024-05-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_tracker', '0002_alter_books_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_auth_name',
            field=models.CharField(default='Author', max_length=254),
        ),
        migrations.AddField(
            model_name='books',
            name='book_num',
            field=models.IntegerField(default=1),
        ),
    ]
